title: Thomas Owtschinnikow
description: AI and Prompt Engineer
#baseurl: ""
url: https://piazzai.github.io/cvless

#theme: cvless

# site settings
#taglong: AI and Prompt Engineer
#tagshort: "- CV Information"

# author settings
author:
  name: Thomas Owtschinnikow
  email: owtschinnikow.thomas@gmail.com
photo: assets/files/photo.jpg
address: Somewhere in Limassol 
phone: 

# social media links
social:
 # facebook: username
  github: ThomasGITgo777
 # instagram: username
  linkedin: thomasowtschinnikow
 # stackoverflow: 0000000/username
 # x: username

# build settings
permalink: pretty
exclude:
  - docker-compose.yml
  - LICENSE
  - README.md
